#Hunspell dictionaries path
# will look for dictionaries at ~/.local/share/fastspell if empty
dictpath: ""

#This is how hunspell files (.dic and .aff) are named in dictpath
hunspell_codes:
    af: af_ZA
    an: an_ES
    ar: ar
    az: az_AZ
    be: be_BY
    bg: bg_BG
    bn: bn_BD
    bs: bs_BA
    ca: ca_ES
    cs: cs_CZ
    cy: cy
    da: da_DK
    de: de_DE
    en: en_EN
    es: es_ES
    et: et_ET
    fa: fa_FA
    fi: fi_FI
    fo: fo
    ga: ga
    gl: gl_ES
    gu: gu_IN
    hbs_lat: hr_HR
    hbs_cyr: sr_RS
    hi: hi_IN
    hr: hr_HR
    hu: hu_HU
    id: id_ID
    is: is_IS
    kk: kk_KZ
    kn: kn_IN
    ky: ky_KG
    lo: lo_LA
    lt: lt
    lv: lv
    me: sr_ME
    mk: mk_MK
    ml: ml_IN
    mr: mr_IN
    ms: ms_MY
    nb: nb_NO
    ne: ne_NP
    nl: nl_NL
    nn: nn_NO
    pl: pl
    pt: pt_PT
    ru: ru_RU
    sk: sk_SK
    sl: sl_SI
    so: so_SO
    sq: sq_AL
    sr: sr_RS
    sv: sv_SE   
    ta: ta_IN
    te: te_IN
    tg: tg_TG
    th: th_TH
    tt: tt_RU
    uk: uk_UA
    ur: ur_PK