#Hunspell dictionaries path
# will look for dictionaries at ~/.local/share/fastspell if empty
dictpath: ""

#This is how hunspell files (.dic and .aff) are named in dictpath
hunspell_codes:
    af: af_ZA
    ar: ar
    bg: bg_BG
    bn: bn_BD
    bs: bs_BA
    ca: ca_ES
    cs: cs_CZ
    da: da_DK
    de: de_DE
    es: es_ES
    et: et_ET
    fa: fa_FA
    gl: gl_ES
    gu: gu_IN
    hbs_lat: hr_HR
    hbs_cyr: sr_RS
    hi: hi_IN
    hr: hr_HR
    hu: hu_HU
    is: is_IS
    kn: kn_IN
    me: sr_ME
    mk: mk_MK
    ml: ml_IN
    mr: mr_IN
    nb: nb_NO
    ne: ne_NP
    nl: nl_NL
    nn: nn_NO
    pt: pt_PT
    ru: ru_RU
    sk: sk_SK
    sl: sl_SI
    sq: sq_AL
    sr: sr_RS
    sv: sv_SE   
    ta: ta_IN
    ur: ur_PK