#Target langs (keys) dict for mistakeable languages (values)
similar:
    ar: [fa, ar]
    af: [nl, de, af]
    be: [ru, uk, be]    
    bg: [mk, bg]
    bs: [hr, me, sr, sl, bs]
    ca: [es, ca]
    cs: [sk, cs]
    da: [nb, nn, sv, fo, is, da]
    es: [gl, ca, an, es]
    fa: [ar, az, tg, fa]
    gl: [es, pt, gl]
    gu: [mr, bn, hi, ur, ne, gu]
    hbs_lat: [sl, hbs_lat]
    hbs_cyr: [ru, mk, bg,  hbs_cyr]    
    hr: [bs, me, sr, sl, hr]
    id: [ms, id]
    is: [da, nb, nn, de, sv, hu, et, fo, is]
    me: [bs, hr, sr, sl, me]
    mk: [bg, mk]
    ml: [ta, ml]
    nb: [nn, da, sv, nb]
    ne: [mr, hi, ur, bn, gu, ne]
    nl: [af, nl]
    nn: [nb, da, sv, is, fo, nn]
    sk: [cs, sk]
    sl: [hbs_lat, sr, hr, bs, sl]    
    so: [en, fi, cy, kn, so]
    sr: [bs, hr, me, sl, sr]
    ta: [ml, kn, ta]
    tt: [kk, ky, ru, tt]
    uk: [be, ru, uk]