#Target langs (keys) dict for mistakeable languages (values)
similar:
    af: [nl, af]    
    bg: [mk, bg]
    bs: [bs, hr, me, sr, sl]
    ca: [es, ca]
    cs: [sk, cs]
    da: [da, nb]
    es: [es, gl, ca]   
    gl: [es, pt, gl]
    hbs_lat: [hbs_lat, sl]
    hbs_cyr: [hbs_cyr, ru, mk, bg]    
    hr: [bs, hr, me, sr, sl]
    is: [is, da, nb, nn, de, sv, hu, et]
    me: [bs, hr, me, sr, sl]
    mk: [bg, mk]
    nb: [nn, da, nb]
    nl: [nl, af]
    nn: [nb, da, sv, nn]
    sk: [cs, sk]
    sl: [hbs_lat, sr, hr, bs, sl]    
    sr: [bs, hr, me, sr, sl]
    ta: [ml, kn, ta]