#Target langs (keys) dict for mistakeable languages (values)
similar:
    ar: [fa, ar]
    af: [nl, de, af]    
    bg: [mk, bg]
    bs: [hr, me, sr, sl, bs]
    ca: [es, ca]
    cs: [sk, cs]
    da: [nb, da]
    es: [gl, ca, es]
    gl: [es, pt, gl]
    gu: [mr, bn, hi, ur, ne, gu]
    hbs_lat: [sl, hbs_lat]
    hbs_cyr: [ru, mk, bg,  hbs_cyr]    
    hr: [bs, me, sr, sl, hr]
    is: [da, nb, nn, de, sv, hu, et, is]
    me: [bs, hr, sr, sl, me]
    mk: [bg, mk]
    nb: [nn, da, sv, nb]
    ne: [mr, hi, ur, bn, gu, ne]
    nl: [af, nl]
    nn: [nb, da, sv, is, fo, nn]
    sk: [cs, sk]
    sl: [hbs_lat, sr, hr, bs, sl]    
    sr: [bs, hr, me, sl, sr]
    ta: [ml, kn, ta]