#Target langs (keys) dict for mistakeable languages (values)
similar:
    ar: [fa, ar]
    af: [nl, de, af]
    az: [ky, ar, tr, tk, az]
    be: [ru, uk, be]    
    bg: [mk, ru, bg]
    bn: [gu, ne, bn]
    bs: [hr, me, sr, sl, bs]
    ca: [es, ca]
    cs: [sk, cs]
    cy: [ga, en, cy]
    da: [nb, nn, sv, fo, is, da]
    es: [gl, ca, an, es]
    et: [lv, lt, pl, et]
    fa: [ar, az, tg, fa]
    ga: [cy, en, ga]
    gl: [es, pt, gl]
    gu: [mr, bn, hi, ur, ne, gu]
    hbs_lat: [sl, hbs_lat]
    hbs_cyr: [ru, mk, bg,  hbs_cyr]    
    he: [yi, he]
    hi: [ur, mr, ne, gu, hi]
    hr: [bs, me, sr, sl, hr]
    id: [ms, id]
    is: [da, nb, nn, de, sv, hu, et, fo, is]
    kk: [ky, tt, ru, kk]
    kn: [ta, te, kn]
    ky: [ru, kk, tt, ky]
    lt: [pl, et, lv, lt]
    lv: [et, lt, pl, lv]
    me: [bs, hr, sr, sl, me]
    mk: [bg, mk]
    ml: [ta, ml]
    ms: [id, ms]
    nb: [nn, da, sv, nb]
    ne: [mr, hi, ur, bn, gu, ne]
    nl: [af, nl]
    nn: [nb, da, sv, is, fo, nn]
    ru: [be, uk, bg, ru]
    sk: [cs, sk]
    sl: [hbs_lat, sr, hr, bs, sl]    
    so: [en, fi, cy, kn, so]
    sr: [bs, hr, me, sl, sr]
    ta: [ml, kn, ta]
    te: [kn, te]
    th: [lo, th]
    tt: [kk, ky, ru, tt]
    uk: [be, ru, uk]
    ur: [hi, mr, gu, ne, ur]