
{% set rdir = "../.." %}
{% set data = load_setup_py_data(setup_file=''+rdir+'/setup.py', from_recipe_dir=True) %}

package:
  name: fastspell
  version: {{ data.get('version') }}

source:
  path: {{ rdir }}

build:
  string: {{ environ.get('GIT_DESCRIBE_HASH') }}
  preserve_egg_dir: True

requirements:
  build:
    - pip
    - setuptools
    - python>=3.7
    - hunspell
  run:
    - python>=3.7
    - hunspell
    - hunspell-en

about:
  home: https://github.com/mbanon/fastspell
  summary: Targetted language identifier, based on FastText and Hunspell
