#Target langs (keys) dict for mistakeable languages (values)
similar:
    ca: [es, ca]
    bg: [mk, bg]
    bs: [bs, hr, me, sr, sl]
    cs: [sk, cs]    
    da: [da, nb]
    es: [es, gl, ca]
    gl: [es, pt, gl]
    hr: [bs, hr, me, sr, sl]
    me: [bs, hr, me, sr, sl]
    mk: [bg, mk]    
    nb: [nn, da, nb]
    nl: [nl, af]
    nn: [nb, da, nn]
    sk: [cs, sk]
    sr: [bs, hr, me, sr, sl]
    hbs: [hbs, sl] # We have enough with latin hbs because it won't be mixed up with Slovene
    sl: [hbs, sl]
